/* automatically generated by rust-bindgen 0.72.1 */

pub const PAM_SUCCESS: u32 = 0;
pub const PAM_OPEN_ERR: u32 = 1;
pub const PAM_SYMBOL_ERR: u32 = 2;
pub const PAM_SERVICE_ERR: u32 = 3;
pub const PAM_SYSTEM_ERR: u32 = 4;
pub const PAM_BUF_ERR: u32 = 5;
pub const PAM_PERM_DENIED: u32 = 6;
pub const PAM_AUTH_ERR: u32 = 7;
pub const PAM_CRED_INSUFFICIENT: u32 = 8;
pub const PAM_AUTHINFO_UNAVAIL: u32 = 9;
pub const PAM_USER_UNKNOWN: u32 = 10;
pub const PAM_MAXTRIES: u32 = 11;
pub const PAM_NEW_AUTHTOK_REQD: u32 = 12;
pub const PAM_ACCT_EXPIRED: u32 = 13;
pub const PAM_SESSION_ERR: u32 = 14;
pub const PAM_CRED_UNAVAIL: u32 = 15;
pub const PAM_CRED_EXPIRED: u32 = 16;
pub const PAM_CRED_ERR: u32 = 17;
pub const PAM_NO_MODULE_DATA: u32 = 18;
pub const PAM_CONV_ERR: u32 = 19;
pub const PAM_AUTHTOK_ERR: u32 = 20;
pub const PAM_AUTHTOK_RECOVERY_ERR: u32 = 21;
pub const PAM_AUTHTOK_LOCK_BUSY: u32 = 22;
pub const PAM_AUTHTOK_DISABLE_AGING: u32 = 23;
pub const PAM_TRY_AGAIN: u32 = 24;
pub const PAM_IGNORE: u32 = 25;
pub const PAM_ABORT: u32 = 26;
pub const PAM_AUTHTOK_EXPIRED: u32 = 27;
pub const PAM_MODULE_UNKNOWN: u32 = 28;
pub const PAM_BAD_ITEM: u32 = 29;
pub const PAM_CONV_AGAIN: u32 = 30;
pub const PAM_INCOMPLETE: u32 = 31;
pub const PAM_SILENT: u32 = 32768;
pub const PAM_DISALLOW_NULL_AUTHTOK: u32 = 1;
pub const PAM_ESTABLISH_CRED: u32 = 2;
pub const PAM_DELETE_CRED: u32 = 4;
pub const PAM_REINITIALIZE_CRED: u32 = 8;
pub const PAM_REFRESH_CRED: u32 = 16;
pub const PAM_CHANGE_EXPIRED_AUTHTOK: u32 = 32;
pub const PAM_SERVICE: u32 = 1;
pub const PAM_USER: u32 = 2;
pub const PAM_TTY: u32 = 3;
pub const PAM_RHOST: u32 = 4;
pub const PAM_CONV: u32 = 5;
pub const PAM_AUTHTOK: u32 = 6;
pub const PAM_OLDAUTHTOK: u32 = 7;
pub const PAM_RUSER: u32 = 8;
pub const PAM_USER_PROMPT: u32 = 9;
pub const PAM_FAIL_DELAY: u32 = 10;
pub const PAM_XDISPLAY: u32 = 11;
pub const PAM_XAUTHDATA: u32 = 12;
pub const PAM_AUTHTOK_TYPE: u32 = 13;
pub const PAM_DATA_SILENT: u32 = 1073741824;
pub const PAM_PROMPT_ECHO_OFF: u32 = 1;
pub const PAM_PROMPT_ECHO_ON: u32 = 2;
pub const PAM_ERROR_MSG: u32 = 3;
pub const PAM_TEXT_INFO: u32 = 4;
pub const PAM_RADIO_TYPE: u32 = 5;
pub const PAM_BINARY_PROMPT: u32 = 7;
pub const PAM_MAX_NUM_MSG: u32 = 32;
pub const PAM_MAX_MSG_SIZE: u32 = 512;
pub const PAM_MAX_RESP_SIZE: u32 = 512;
pub const PAM_AUTHTOK_RECOVER_ERR: u32 = 21;
pub const PAM_BP_MAX_LENGTH: u32 = 131072;
pub const PAM_BPC_FALSE: u32 = 0;
pub const PAM_BPC_TRUE: u32 = 1;
pub const PAM_BPC_OK: u32 = 1;
pub const PAM_BPC_SELECT: u32 = 2;
pub const PAM_BPC_DONE: u32 = 3;
pub const PAM_BPC_FAIL: u32 = 4;
pub const PAM_BPC_GETENV: u32 = 65;
pub const PAM_BPC_PUTENV: u32 = 66;
pub const PAM_BPC_TEXT: u32 = 67;
pub const PAM_BPC_ERROR: u32 = 68;
pub const PAM_BPC_PROMPT: u32 = 69;
pub const PAM_BPC_PASS: u32 = 70;
pub const PAM_PRELIM_CHECK: u32 = 16384;
pub const PAM_UPDATE_AUTHTOK: u32 = 8192;
pub const PAM_DATA_REPLACE: u32 = 536870912;
pub const PAM_MODUTIL_NGROUPS: u32 = 64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pam_handle {
    _unused: [u8; 0],
}
pub type pam_handle_t = pam_handle;
unsafe extern "C" {
    pub fn pam_set_item(
        pamh: *mut pam_handle_t,
        item_type: ::core::ffi::c_int,
        item: *const ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_get_item(
        pamh: *const pam_handle_t,
        item_type: ::core::ffi::c_int,
        item: *mut *const ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_strerror(
        pamh: *mut pam_handle_t,
        errnum: ::core::ffi::c_int,
    ) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn pam_putenv(
        pamh: *mut pam_handle_t,
        name_value: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_getenv(
        pamh: *mut pam_handle_t,
        name: *const ::core::ffi::c_char,
    ) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn pam_getenvlist(pamh: *mut pam_handle_t) -> *mut *mut ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn pam_fail_delay(
        pamh: *mut pam_handle_t,
        musec_delay: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pam_message {
    pub msg_style: ::core::ffi::c_int,
    pub msg: *const ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pam_message"][::core::mem::size_of::<pam_message>() - 16usize];
    ["Alignment of pam_message"][::core::mem::align_of::<pam_message>() - 8usize];
    ["Offset of field: pam_message::msg_style"]
        [::core::mem::offset_of!(pam_message, msg_style) - 0usize];
    ["Offset of field: pam_message::msg"][::core::mem::offset_of!(pam_message, msg) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pam_response {
    pub resp: *mut ::core::ffi::c_char,
    pub resp_retcode: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pam_response"][::core::mem::size_of::<pam_response>() - 16usize];
    ["Alignment of pam_response"][::core::mem::align_of::<pam_response>() - 8usize];
    ["Offset of field: pam_response::resp"][::core::mem::offset_of!(pam_response, resp) - 0usize];
    ["Offset of field: pam_response::resp_retcode"]
        [::core::mem::offset_of!(pam_response, resp_retcode) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pam_conv {
    pub conv: ::core::option::Option<
        unsafe extern "C" fn(
            num_msg: ::core::ffi::c_int,
            msg: *mut *const pam_message,
            resp: *mut *mut pam_response,
            appdata_ptr: *mut ::core::ffi::c_void,
        ) -> ::core::ffi::c_int,
    >,
    pub appdata_ptr: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pam_conv"][::core::mem::size_of::<pam_conv>() - 16usize];
    ["Alignment of pam_conv"][::core::mem::align_of::<pam_conv>() - 8usize];
    ["Offset of field: pam_conv::conv"][::core::mem::offset_of!(pam_conv, conv) - 0usize];
    ["Offset of field: pam_conv::appdata_ptr"]
        [::core::mem::offset_of!(pam_conv, appdata_ptr) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pam_xauth_data {
    pub namelen: ::core::ffi::c_int,
    pub name: *mut ::core::ffi::c_char,
    pub datalen: ::core::ffi::c_int,
    pub data: *mut ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pam_xauth_data"][::core::mem::size_of::<pam_xauth_data>() - 32usize];
    ["Alignment of pam_xauth_data"][::core::mem::align_of::<pam_xauth_data>() - 8usize];
    ["Offset of field: pam_xauth_data::namelen"]
        [::core::mem::offset_of!(pam_xauth_data, namelen) - 0usize];
    ["Offset of field: pam_xauth_data::name"]
        [::core::mem::offset_of!(pam_xauth_data, name) - 8usize];
    ["Offset of field: pam_xauth_data::datalen"]
        [::core::mem::offset_of!(pam_xauth_data, datalen) - 16usize];
    ["Offset of field: pam_xauth_data::data"]
        [::core::mem::offset_of!(pam_xauth_data, data) - 24usize];
};
unsafe extern "C" {
    pub fn pam_start(
        service_name: *const ::core::ffi::c_char,
        user: *const ::core::ffi::c_char,
        pam_conversation: *const pam_conv,
        pamh: *mut *mut pam_handle_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_start_confdir(
        service_name: *const ::core::ffi::c_char,
        user: *const ::core::ffi::c_char,
        pam_conversation: *const pam_conv,
        confdir: *const ::core::ffi::c_char,
        pamh: *mut *mut pam_handle_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_end(pamh: *mut pam_handle_t, pam_status: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_authenticate(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_setcred(pamh: *mut pam_handle_t, flags: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_acct_mgmt(pamh: *mut pam_handle_t, flags: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_open_session(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_close_session(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_chauthtok(pamh: *mut pam_handle_t, flags: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
pub type __uid_t = ::core::ffi::c_uint;
pub type __gid_t = ::core::ffi::c_uint;
pub type __time_t = ::core::ffi::c_long;
pub type gid_t = __gid_t;
pub type uid_t = __uid_t;
pub type __gnuc_va_list = __builtin_va_list;
pub type va_list = __gnuc_va_list;
pub type time_t = __time_t;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct _bindgen_ty_4 {
    pub length: u32,
    pub control: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _bindgen_ty_4"][::core::mem::size_of::<_bindgen_ty_4>() - 5usize];
    ["Alignment of _bindgen_ty_4"][::core::mem::align_of::<_bindgen_ty_4>() - 1usize];
    ["Offset of field: _bindgen_ty_4::length"]
        [::core::mem::offset_of!(_bindgen_ty_4, length) - 0usize];
    ["Offset of field: _bindgen_ty_4::control"]
        [::core::mem::offset_of!(_bindgen_ty_4, control) - 4usize];
};
pub type pamc_bp_t = *mut _bindgen_ty_4;
unsafe extern "C" {
    pub fn pam_vsyslog(
        pamh: *const pam_handle_t,
        priority: ::core::ffi::c_int,
        fmt: *const ::core::ffi::c_char,
        args: *mut __va_list_tag,
    );
}
unsafe extern "C" {
    pub fn pam_syslog(
        pamh: *const pam_handle_t,
        priority: ::core::ffi::c_int,
        fmt: *const ::core::ffi::c_char,
        ...
    );
}
unsafe extern "C" {
    pub fn pam_vprompt(
        pamh: *mut pam_handle_t,
        style: ::core::ffi::c_int,
        response: *mut *mut ::core::ffi::c_char,
        fmt: *const ::core::ffi::c_char,
        args: *mut __va_list_tag,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_prompt(
        pamh: *mut pam_handle_t,
        style: ::core::ffi::c_int,
        response: *mut *mut ::core::ffi::c_char,
        fmt: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_get_authtok(
        pamh: *mut pam_handle_t,
        item: ::core::ffi::c_int,
        authtok: *mut *const ::core::ffi::c_char,
        prompt: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_get_authtok_noverify(
        pamh: *mut pam_handle_t,
        authtok: *mut *const ::core::ffi::c_char,
        prompt: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_get_authtok_verify(
        pamh: *mut pam_handle_t,
        authtok: *mut *const ::core::ffi::c_char,
        prompt: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub static mut pam_misc_conv_warn_time: time_t;
}
unsafe extern "C" {
    pub static mut pam_misc_conv_die_time: time_t;
}
unsafe extern "C" {
    pub static mut pam_misc_conv_warn_line: *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub static mut pam_misc_conv_die_line: *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub static mut pam_misc_conv_died: ::core::ffi::c_int;
}
unsafe extern "C" {
    pub static mut pam_binary_handler_fn: ::core::option::Option<
        unsafe extern "C" fn(
            appdata: *mut ::core::ffi::c_void,
            prompt_p: *mut pamc_bp_t,
        ) -> ::core::ffi::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pam_binary_handler_free: ::core::option::Option<
        unsafe extern "C" fn(appdata: *mut ::core::ffi::c_void, prompt_p: *mut pamc_bp_t),
    >;
}
unsafe extern "C" {
    pub fn pam_misc_paste_env(
        pamh: *mut pam_handle_t,
        user_env: *const *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_misc_drop_env(env: *mut *mut ::core::ffi::c_char) -> *mut *mut ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn pam_misc_setenv(
        pamh: *mut pam_handle_t,
        name: *const ::core::ffi::c_char,
        value: *const ::core::ffi::c_char,
        readonly: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_set_data(
        pamh: *mut pam_handle_t,
        module_data_name: *const ::core::ffi::c_char,
        data: *mut ::core::ffi::c_void,
        cleanup: ::core::option::Option<
            unsafe extern "C" fn(
                pamh: *mut pam_handle_t,
                data: *mut ::core::ffi::c_void,
                error_status: ::core::ffi::c_int,
            ),
        >,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_get_data(
        pamh: *const pam_handle_t,
        module_data_name: *const ::core::ffi::c_char,
        data: *mut *const ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_get_user(
        pamh: *mut pam_handle_t,
        user: *mut *const ::core::ffi::c_char,
        prompt: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_sm_authenticate(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
        argc: ::core::ffi::c_int,
        argv: *mut *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_sm_setcred(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
        argc: ::core::ffi::c_int,
        argv: *mut *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_sm_acct_mgmt(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
        argc: ::core::ffi::c_int,
        argv: *mut *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_sm_open_session(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
        argc: ::core::ffi::c_int,
        argv: *mut *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_sm_close_session(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
        argc: ::core::ffi::c_int,
        argv: *mut *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_sm_chauthtok(
        pamh: *mut pam_handle_t,
        flags: ::core::ffi::c_int,
        argc: ::core::ffi::c_int,
        argv: *mut *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct passwd {
    pub pw_name: *mut ::core::ffi::c_char,
    pub pw_passwd: *mut ::core::ffi::c_char,
    pub pw_uid: __uid_t,
    pub pw_gid: __gid_t,
    pub pw_gecos: *mut ::core::ffi::c_char,
    pub pw_dir: *mut ::core::ffi::c_char,
    pub pw_shell: *mut ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of passwd"][::core::mem::size_of::<passwd>() - 48usize];
    ["Alignment of passwd"][::core::mem::align_of::<passwd>() - 8usize];
    ["Offset of field: passwd::pw_name"][::core::mem::offset_of!(passwd, pw_name) - 0usize];
    ["Offset of field: passwd::pw_passwd"][::core::mem::offset_of!(passwd, pw_passwd) - 8usize];
    ["Offset of field: passwd::pw_uid"][::core::mem::offset_of!(passwd, pw_uid) - 16usize];
    ["Offset of field: passwd::pw_gid"][::core::mem::offset_of!(passwd, pw_gid) - 20usize];
    ["Offset of field: passwd::pw_gecos"][::core::mem::offset_of!(passwd, pw_gecos) - 24usize];
    ["Offset of field: passwd::pw_dir"][::core::mem::offset_of!(passwd, pw_dir) - 32usize];
    ["Offset of field: passwd::pw_shell"][::core::mem::offset_of!(passwd, pw_shell) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct group {
    pub gr_name: *mut ::core::ffi::c_char,
    pub gr_passwd: *mut ::core::ffi::c_char,
    pub gr_gid: __gid_t,
    pub gr_mem: *mut *mut ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of group"][::core::mem::size_of::<group>() - 32usize];
    ["Alignment of group"][::core::mem::align_of::<group>() - 8usize];
    ["Offset of field: group::gr_name"][::core::mem::offset_of!(group, gr_name) - 0usize];
    ["Offset of field: group::gr_passwd"][::core::mem::offset_of!(group, gr_passwd) - 8usize];
    ["Offset of field: group::gr_gid"][::core::mem::offset_of!(group, gr_gid) - 16usize];
    ["Offset of field: group::gr_mem"][::core::mem::offset_of!(group, gr_mem) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct spwd {
    pub sp_namp: *mut ::core::ffi::c_char,
    pub sp_pwdp: *mut ::core::ffi::c_char,
    pub sp_lstchg: ::core::ffi::c_long,
    pub sp_min: ::core::ffi::c_long,
    pub sp_max: ::core::ffi::c_long,
    pub sp_warn: ::core::ffi::c_long,
    pub sp_inact: ::core::ffi::c_long,
    pub sp_expire: ::core::ffi::c_long,
    pub sp_flag: ::core::ffi::c_ulong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of spwd"][::core::mem::size_of::<spwd>() - 72usize];
    ["Alignment of spwd"][::core::mem::align_of::<spwd>() - 8usize];
    ["Offset of field: spwd::sp_namp"][::core::mem::offset_of!(spwd, sp_namp) - 0usize];
    ["Offset of field: spwd::sp_pwdp"][::core::mem::offset_of!(spwd, sp_pwdp) - 8usize];
    ["Offset of field: spwd::sp_lstchg"][::core::mem::offset_of!(spwd, sp_lstchg) - 16usize];
    ["Offset of field: spwd::sp_min"][::core::mem::offset_of!(spwd, sp_min) - 24usize];
    ["Offset of field: spwd::sp_max"][::core::mem::offset_of!(spwd, sp_max) - 32usize];
    ["Offset of field: spwd::sp_warn"][::core::mem::offset_of!(spwd, sp_warn) - 40usize];
    ["Offset of field: spwd::sp_inact"][::core::mem::offset_of!(spwd, sp_inact) - 48usize];
    ["Offset of field: spwd::sp_expire"][::core::mem::offset_of!(spwd, sp_expire) - 56usize];
    ["Offset of field: spwd::sp_flag"][::core::mem::offset_of!(spwd, sp_flag) - 64usize];
};
unsafe extern "C" {
    pub fn pam_modutil_check_user_in_passwd(
        pamh: *mut pam_handle_t,
        user_name: *const ::core::ffi::c_char,
        file_name: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_getpwnam(
        pamh: *mut pam_handle_t,
        user: *const ::core::ffi::c_char,
    ) -> *mut passwd;
}
unsafe extern "C" {
    pub fn pam_modutil_getpwuid(pamh: *mut pam_handle_t, uid: uid_t) -> *mut passwd;
}
unsafe extern "C" {
    pub fn pam_modutil_getgrnam(
        pamh: *mut pam_handle_t,
        group: *const ::core::ffi::c_char,
    ) -> *mut group;
}
unsafe extern "C" {
    pub fn pam_modutil_getgrgid(pamh: *mut pam_handle_t, gid: gid_t) -> *mut group;
}
unsafe extern "C" {
    pub fn pam_modutil_getspnam(
        pamh: *mut pam_handle_t,
        user: *const ::core::ffi::c_char,
    ) -> *mut spwd;
}
unsafe extern "C" {
    pub fn pam_modutil_user_in_group_nam_nam(
        pamh: *mut pam_handle_t,
        user: *const ::core::ffi::c_char,
        group: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_user_in_group_nam_gid(
        pamh: *mut pam_handle_t,
        user: *const ::core::ffi::c_char,
        group: gid_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_user_in_group_uid_nam(
        pamh: *mut pam_handle_t,
        user: uid_t,
        group: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_user_in_group_uid_gid(
        pamh: *mut pam_handle_t,
        user: uid_t,
        group: gid_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_getlogin(pamh: *mut pam_handle_t) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn pam_modutil_read(
        fd: ::core::ffi::c_int,
        buffer: *mut ::core::ffi::c_char,
        count: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_write(
        fd: ::core::ffi::c_int,
        buffer: *const ::core::ffi::c_char,
        count: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_audit_write(
        pamh: *mut pam_handle_t,
        type_: ::core::ffi::c_int,
        message: *const ::core::ffi::c_char,
        retval: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pam_modutil_privs {
    pub grplist: *mut gid_t,
    pub number_of_groups: ::core::ffi::c_int,
    pub allocated: ::core::ffi::c_int,
    pub old_gid: gid_t,
    pub old_uid: uid_t,
    pub is_dropped: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pam_modutil_privs"][::core::mem::size_of::<pam_modutil_privs>() - 32usize];
    ["Alignment of pam_modutil_privs"][::core::mem::align_of::<pam_modutil_privs>() - 8usize];
    ["Offset of field: pam_modutil_privs::grplist"]
        [::core::mem::offset_of!(pam_modutil_privs, grplist) - 0usize];
    ["Offset of field: pam_modutil_privs::number_of_groups"]
        [::core::mem::offset_of!(pam_modutil_privs, number_of_groups) - 8usize];
    ["Offset of field: pam_modutil_privs::allocated"]
        [::core::mem::offset_of!(pam_modutil_privs, allocated) - 12usize];
    ["Offset of field: pam_modutil_privs::old_gid"]
        [::core::mem::offset_of!(pam_modutil_privs, old_gid) - 16usize];
    ["Offset of field: pam_modutil_privs::old_uid"]
        [::core::mem::offset_of!(pam_modutil_privs, old_uid) - 20usize];
    ["Offset of field: pam_modutil_privs::is_dropped"]
        [::core::mem::offset_of!(pam_modutil_privs, is_dropped) - 24usize];
};
unsafe extern "C" {
    pub fn pam_modutil_drop_priv(
        pamh: *mut pam_handle_t,
        p: *mut pam_modutil_privs,
        pw: *const passwd,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_regain_priv(
        pamh: *mut pam_handle_t,
        p: *mut pam_modutil_privs,
    ) -> ::core::ffi::c_int;
}
impl pam_modutil_redirect_fd {
    pub const PAM_MODUTIL_IGNORE_FD: pam_modutil_redirect_fd = pam_modutil_redirect_fd(0);
    pub const PAM_MODUTIL_PIPE_FD: pam_modutil_redirect_fd = pam_modutil_redirect_fd(1);
    pub const PAM_MODUTIL_NULL_FD: pam_modutil_redirect_fd = pam_modutil_redirect_fd(2);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct pam_modutil_redirect_fd(pub ::core::ffi::c_uint);
unsafe extern "C" {
    pub fn pam_modutil_sanitize_helper_fds(
        pamh: *mut pam_handle_t,
        redirect_stdin: pam_modutil_redirect_fd,
        redirect_stdout: pam_modutil_redirect_fd,
        redirect_stderr: pam_modutil_redirect_fd,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn pam_modutil_search_key(
        pamh: *mut pam_handle_t,
        file_name: *const ::core::ffi::c_char,
        key: *const ::core::ffi::c_char,
    ) -> *mut ::core::ffi::c_char;
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: ::core::ffi::c_uint,
    pub fp_offset: ::core::ffi::c_uint,
    pub overflow_arg_area: *mut ::core::ffi::c_void,
    pub reg_save_area: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __va_list_tag"][::core::mem::size_of::<__va_list_tag>() - 24usize];
    ["Alignment of __va_list_tag"][::core::mem::align_of::<__va_list_tag>() - 8usize];
    ["Offset of field: __va_list_tag::gp_offset"]
        [::core::mem::offset_of!(__va_list_tag, gp_offset) - 0usize];
    ["Offset of field: __va_list_tag::fp_offset"]
        [::core::mem::offset_of!(__va_list_tag, fp_offset) - 4usize];
    ["Offset of field: __va_list_tag::overflow_arg_area"]
        [::core::mem::offset_of!(__va_list_tag, overflow_arg_area) - 8usize];
    ["Offset of field: __va_list_tag::reg_save_area"]
        [::core::mem::offset_of!(__va_list_tag, reg_save_area) - 16usize];
};
